version: '3.8'
services:
  sqlserver:
    hostname: sqlserver
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    user: "1000:1000"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - CONTAINER_FOLDER=${CONTAINER_FOLDER:-container-folder}
    ports:
      - "1433:1433"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /${CONTAINER_FOLDER}/sql-server:/var/opt/mssql